
Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MutableConstant:
  Enabled: false
